import http from './http'

export const login = (username, password) => http.post('/auth/login', { username, password })
export const me = () => http.get('/auth/me')
export const logout = () => http.post('/auth/logout')

export const listPolicies = () => http.get('/policies')
export const getPolicy = (id) => http.get(`/policies/${id}`)
export const getPolicyTemplate = () => http.get('/policies/default-template')
export const createPolicy = (payload) => http.post('/policies', payload)
export const updatePolicy = (id, payload) => http.put(`/policies/${id}`, payload)
export const deletePolicy = (id) => http.delete(`/policies/${id}`)
export const enablePolicy = (id) => http.post(`/policies/${id}/enable`)
export const disablePolicy = (id) => http.post(`/policies/${id}/disable`)
export const deployPolicy = (id) => http.post(`/policies/${id}/deploy`)
export const scaleModule = (id, module, replicas) => http.post(`/policies/${id}/modules/${module}/scale`, { replicas })
export const policyRuntime = (id) => http.get(`/policies/${id}/runtime`)

export const listTasks = (params) => http.get('/tasks', { params })
export const createTask = (payload) => http.post('/tasks', payload)
export const getTask = (id) => http.get(`/tasks/${id}`)
export const deleteTask = (id) => http.delete(`/tasks/${id}`)
export const pauseTask = (id) => http.post(`/tasks/${id}/pause`)
export const resumeTask = (id) => http.post(`/tasks/${id}/resume`)
export const terminateTask = (id) => http.post(`/tasks/${id}/terminate`)
export const restartTask = (id) => http.post(`/tasks/${id}/restart`)
export const taskParts = (id) => http.get(`/tasks/${id}/parts`)
export const taskEvents = (id) => http.get(`/tasks/${id}/events`)
export const taskPorts = (id) => http.get(`/tasks/${id}/results/ports`)
export const taskServices = (id) => http.get(`/tasks/${id}/results/services`)
export const taskVulns = (id) => http.get(`/tasks/${id}/results/vulnerabilities`)
export const taskWeaks = (id) => http.get(`/tasks/${id}/results/weak-passwords`)

export const resSummary = () => http.get('/resources/summary')
export const resNodes = () => http.get('/resources/nodes')
export const resPods = () => http.get('/resources/pods')
export const resPolicyPods = (id) => http.get(`/resources/policies/${id}/pods`)
export const resStreams = (policyID) => http.get('/resources/streams', { params: { policy_id: policyID } })
